[build]
target = "tc32-unknown-none-elf"

[target.tc32-unknown-none-elf]
rustflags = [
    "-C", "llvm-args=-enable-tail-merge=false",
    "-C", "link-arg=--gc-sections",
]

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
